version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
